services:
  - type: web
    name: quart-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: hypercorn app:app --bind 0.0.0.0:$PORT
    disk:
      name: sqlite
      mountPath: /data
      sizeGB: 1
